// EDIT TITLES, INTRODUCTIONS AND QUESTIONS in lessons below.
// EDIT REVEALED EXPLANATIONS by searching for $('answer').innerHTML.
// EDIT FOOTER EQUATIONS in content.js.
'use strict';
const $=id=>document.getElementById(id), E=Economics, fmt=x=>Math.abs(x)<1e-8?'0':x.toLocaleString('en-US',{maximumFractionDigits:2});
const defaults={static:{a:100,b:1,c:20,d:.5,p:60},dynamic:{a1:100,b1:1,c1:20,d1:0,a2:100,b2:1,c2:20,d2:0,S:100,r:10,years:1,q1:50,q2:50}};
let s={...defaults.static}, t={...defaults.dynamic}, slide=0, revealed=false;
const lessons=[
{tab:'1 · Price & surplus',title:'Fix a price and see who profits.',intro:'You are a solar panel producer. Set a uniform selling price. We will meet the resulting demand and inspect the benefits and costs.',question:'Does a higher selling price always give the producer more surplus?'},
{tab:'2 · Static efficiency',title:'What quantity creates the most value?',intro:'Find the quantity that maximizes consumer plus producer surplus. This is the efficient point.',question:'What happens to total surplus when you produce more than the demand–cost intersection?'},
{tab:'3 · Market power',title:'Monopolies play a different game.',intro:'Compare a monopolist’s profit-maximizing choice with the allocation that maximizes total surplus. Would they meet the consumer demand or maximize the company revenue?',question:'Why does the profit-maximizing monopolist restrict output?'},
{tab:'4 · Across time',title:'A finite resource has more than one use.',intro:'Allocate the stock between today and a future period. The allocated stocks over the periods will be bounded by the available stock.',question:'Is splitting the stock equally a good choice?'},
{tab:'5 · Discounting',title:'How much is a future benefit worth today?',intro:'Keep demand and costs fixed. Change the discount rate or the time between periods, then compare your allocation with the optimum.',question:'How does a higher discount rate change the efficient allocation?'}
];
const dynamic=()=>slide>=3;
function field(key,label,min,max,step,model){return `<label class="field"><span>${label}</span><input type="number" data-param="${key}" aria-label="${label}" min="${min}" max="${max}" step="${step}" value="${model[key]}" required></label>`;}
function choice(key,label,max,value){return `<label class="field"><span>${label}<input type="number" data-choice="${key}" aria-label="${label}" min="0" max="${max}" step="any" value="${value}"></span><input type="range" data-choice="${key}" aria-label="${label} slider" min="0" max="${max}" step="${max/1000||.01}" value="${value}"></label>`;}
function render(){const l=lessons[slide];$('nav').innerHTML=lessons.map((v,i)=>`<button data-slide="${i}" ${i===slide?'aria-current="step"':''}>${v.tab}</button>`).join('');$('eyebrow').textContent=dynamic()?'Dynamic efficiency · finite resource':'Static efficiency · single period';$('title').textContent=l.title;$('intro').textContent=l.intro;$('question').textContent=l.question;$('counter').textContent=`${slide+1} / ${lessons.length}`;$('prev').disabled=slide===0;$('next').disabled=slide===lessons.length-1;
$('parameters').innerHTML=dynamic()?field('a1','Today: demand intercept a₁',1,5000,.1,t)+field('b1','Today: demand slope b₁',.1,100,.01,t)+field('c1','Today: cost intercept c₁',0,5000,.1,t)+field('d1','Today: cost slope d₁',0,100,.01,t)+field('a2','Future: demand intercept a₂',1,5000,.1,t)+field('b2','Future: demand slope b₂',.1,100,.01,t)+field('c2','Future: cost intercept c₂',0,5000,0.1,t)+field('d2','Future: cost slope d₂',0,100,.01,t)+field('S','Available stock S',1,500,1,t)+field('r','Annual discount rate (%)',0,99,.05,t)+field('years','Years between periods',1,50,1,t):field('a','Demand intercept a',0.1,50000,0.01,s)+field('b','Demand slope b',.01,100,.01,s)+field('c','Cost intercept c',0,5000,0.1,s)+field('d','Cost slope d',0,100,.01,s);
$('assumption').innerHTML=dynamic()?'One homogeneous, nonrenewable resource; certain demand and costs; no externalities or fixed costs. Unused stock has zero terminal value.':'Demand intercept : Price at which the last customer buys (beyond this no sales are made). <br> Cost intercept : Price at which last unit is sold (below this no sales are feasible). <br>Demand Price = a + b*quantity. Marginal cost = c +d*quantity. <br>No fixed costs, taxes, or externalities.';
$('equations').innerHTML=dynamic()?FOOTER_CONTENT.dynamic:FOOTER_CONTENT.static;
$('graphs').innerHTML=dynamic()?'<h3>Today and discounted future on one graph</h3><div class="chart" id="allocation-chart"></div><div class="legend"><span class="demand">Blue: today MNB</span><span class="cost">Orange: future MNB</span><span class="loss">Dashed red: discounted future MNB</span></div><p id="allocation-note" class="assumption"></p><details><summary>Separate period graphs and consumer / producer surplus</summary><div class="charts"><div class="chart" id="chart1"><h3>Today</h3></div><div class="chart" id="chart2"><h3>Future (undiscounted)</h3></div></div></details>':'<div class="chart" id="chart1"></div>';$('losslegend').hidden=dynamic();refresh();}
function bound(){s.p=E.clamp(s.p,0,s.a);t.q1=E.clamp(t.q1,0,Math.min(t.S,t.a1/t.b1));t.q2=E.clamp(t.q2,0,Math.min(t.S-t.q1,t.a2/t.b2));}
function metrics(items){$('metrics').innerHTML=items.map(([label,value,unit])=>`<div class="metric"><span>${label}</span><strong>${fmt(value)}</strong> <small>${unit||'$'}</small></div>`).join('');}
function refresh(updateControls=true){bound();if(dynamic()){const o=E.dynamic(t);if(updateControls)$('choices').innerHTML=choice('q1','Extract today q₁',Math.min(t.S,t.a1/t.b1),t.q1)+choice('q2','Extract in future q₂',Math.min(t.S,t.a2/t.b2),t.q2)+'<button data-action="optimum">Use efficient allocation</button><button data-action="textbook">Textbook example</button>';
plotAllocation(o);plot('chart1',t.a1,t.b1,t.c1,t.d1,o.o1,revealed?o.u1:null,false);plot('chart2',t.a2,t.b2,t.c2,t.d2,o.o2,revealed?o.u2:null,false);
metrics([['Today’s net benefit',o.o1.ts],['Future’s net benefit',o.o2.ts],['Present-value total',o.pv],['Unused stock',o.unused,'units']]);$('status').textContent=`Today’s marginal net benefit: $${fmt(o.mnb1)}/unit. Discounted future marginal net benefit: $${fmt(o.mnb2)}/unit. Future discount factor: ${fmt(1/o.discount)}.`;
$('answer').innerHTML=`<p>The efficient allocation is <b>${fmt(o.u1)} units today</b> and <b>${fmt(o.u2)} units in the future</b>, leaving ${fmt(Math.max(0,t.S-o.u1-o.u2))} unused. Maximum present-value surplus: <b>$${fmt(o.best)}</b>. Your allocation is $${fmt(Math.max(0,o.best-o.pv))} below it.</p><p>${o.lambda>1e-7?'The stock is scarce. With positive extraction in both periods, efficiency equalizes today’s marginal net benefit and the discounted future marginal net benefit. At a corner, moving a unit to the unused period cannot improve welfare.':'The stock is abundant. Each period reaches its own P = MC quantity; forcing extraction of the remaining stock would not increase welfare.'}</p><p>${slide===4?'A higher rate reduces the weight on future benefits. When stock is binding and both periods are active, this shifts extraction toward today. The rate has no allocation effect when both periods already reach their unconstrained optima.':'Equal quantities are efficient only for particular combinations of demand, costs, and discounting.'}</p>`;
}else{const o=E.stat(s);if(updateControls)$('choices').innerHTML=choice('p','Selling price ($ / unit)',s.a,s.p)+(slide>0?'<button data-action="efficient">Use efficient price</button>':'')+(slide===2?'<button data-action="monopoly">Use monopoly price</button>':'');plot('chart1',s.a,s.b,s.c,s.d,o,revealed?o.qe:null,true);metrics([['Consumer surplus',o.cs],['Producer surplus',o.ps],['Total surplus',o.ts],['Deadweight loss',o.dwl]]);$('status').textContent=`Quantity sold: ${fmt(o.q)} units · Revenue: $${fmt(o.revenue)} · Variable cost: $${fmt(o.cost)}${o.ps<0?' · The supplier makes a loss at this price.':''}`;
$('answer').innerHTML=`<p>Efficient output: <b>${fmt(o.qe)} units</b> at demand price <b>$${fmt(o.pe)}</b>.</p><p>${slide===0?'A higher price increases the revenue per unit but reduces the sales. Producer surplus is revenue (i.e. price*quantity) minus the area under marginal cost (i.e. total cost); consumer surplus is the area below the demand curve and above the set price.':slide===1?'At the efficient output, willingness to pay equals marginal cost. Below it, mutually beneficial units go unproduced. Above it, extra units cost you more than what buyers will pay. Both cause deadweight loss.':'A uniform-price monopolist faces marginal revenue below demand: selling another unit also lowers the price received on all earlier units. It chooses MR = MC when output is positive, whereas welfare maximization uses P = MC.'}</p><p>${s.c>=s.a?'Here even the first unit costs at least as much as buyers value it, so the efficient and profit-maximizing quantities are zero.':'The dashed red line marks the efficient quantity. The pink area is the welfare lost relative to that quantity.'}</p>`;
}
$('benchmarklegend').hidden=!revealed;$('answer').hidden=!revealed;$('reveal').textContent=revealed?'Hide explanation & benchmark':'Reveal explanation & benchmark';}
function plot(id,a,b,c,d,o,benchmark,clickable){const el=$(id),old=el.querySelector('svg');if(old)old.remove();el.querySelector('.period-details')?.remove();const w=Math.max(250,el.clientWidth),h=dynamic()?300:360,L=62,R=16,T=28,B=54,pw=w-L-R,ph=h-T-B,qmax=a/b,ymax=Math.max(a,c+d*qmax)*1.1;const X=q=>L+q/qmax*pw,Y=p=>T+ph-p/ymax*ph;let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Demand and marginal cost with surplus areas. Quantity ${fmt(o.q)}, price ${fmt(o.p)}."><defs><pattern id="hatch-${id}" width="6" height="6" patternUnits="userSpaceOnUse"><path d="M0,6 L6,0" stroke="#ad5200" stroke-width="1"/></pattern></defs><rect x="${L}" y="${T}" width="${pw}" height="${ph}" fill="white" stroke="#dce3eb"/>`;
const path=(pts,fill,opacity=1,stroke='none',dash='')=>`<path d="${pts.map((p,i)=>(i?'L':'M')+X(p[0])+','+Y(p[1])).join(' ')}${fill==='none'?'':' Z'}" fill="${fill}" opacity="${opacity}" stroke="${stroke}" stroke-width="2" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
svg+=path([[0,a],[o.q,a-b*o.q],[0,o.p]],'#bbdcf7');let cross=d>0?E.clamp((o.p-c)/d,0,o.q):(o.p>=c?o.q:0);if(cross>0)svg+=path([[0,o.p],[cross,o.p],[cross,c+d*cross],[0,c]],'#f2cc99');if(cross<o.q)svg+=path([[cross,o.p],[o.q,o.p],[o.q,c+d*o.q],[cross,c+d*cross]],`url(#hatch-${id})`);
if(clickable){const qe=Math.max(0,(a-c)/(b+d)),l=Math.min(qe,o.q),r=Math.max(qe,o.q);svg+=path([[l,a-b*l],[r,a-b*r],[r,c+d*r],[l,c+d*l]],'#dba5b1',.65);}
for(let i=0;i<=4;i++){let q=qmax*i/4,p=ymax*i/4;svg+=`<text x="${X(q)}" y="${h-B+22}" text-anchor="${i===4?'end':i===0?'start':'middle'}">${fmt(q)}</text><text x="${L-8}" y="${Y(p)+4}" text-anchor="end">${fmt(p)}</text>`;}
svg+=path([[0,a],[qmax,0]],'none',1,'#1865ac')+path([[0,c],[qmax,c+d*qmax]],'none',1,'#ad5200')+path([[0,o.p],[o.q,o.p],[o.q,0]],'none',1,'#526277','5 4');if (slide === 2) {
    const qMRzero = a / (2 * b);
  
    svg += path(
      [[0, a], [qMRzero, 0]],
      'none',
      0.2,
      '#7a3db8',
      '7 4'
    );svg += `
    <text
      x="${X(qMRzero * 0.89)}"
      y="${Y(a - 2 * b * qMRzero * 0.89) - 8}"
      fill="#7a3db8"
      font-weight="600">
      MR
    </text>
  `;
  }if(benchmark!==null)svg+=path([[benchmark,0],[benchmark,ymax]],'none',1,'#ac1932','4 4');svg+=`<circle cx="${X(o.q)}" cy="${Y(o.p)}" r="6" fill="#172b42" stroke="white" stroke-width="2"/><text x="${L}" y="17">p = ${fmt(o.p)}; q = ${fmt(o.q)}</text><text class="axis-title" x="${L+pw/2}" y="${h-7}" text-anchor="middle">Quantity</text><text class="axis-title" transform="translate(16 ${T+ph/2}) rotate(-90)" text-anchor="middle">Price per unit</text>`;
if(clickable)svg+=`<rect data-hit="true" x="${L}" y="${T}" width="${pw}" height="${ph}" fill="transparent" style="cursor:crosshair"><title>Click to choose a quantity on demand. Use the price control for keyboard input.</title></rect>`;svg+='</svg>';el.insertAdjacentHTML('beforeend',svg);if(!clickable)el.insertAdjacentHTML('beforeend',`<p class="period-details">CS $${fmt(o.cs)} · PS $${fmt(o.ps)}</p>`);if(clickable)el.querySelector('[data-hit]').addEventListener('click',e=>{const rect=el.querySelector('svg').getBoundingClientRect(),q=E.clamp(((e.clientX-rect.left)*w/rect.width-L)/pw*qmax,0,qmax);s.p=a-b*q;refresh();});}
// Combined resource-allocation diagram: the future quantity runs right to left.
function plotAllocation(o){
 const el=$('allocation-chart'),w=Math.max(280,el.clientWidth),h=400,L=66,R=22,T=24,B=92,pw=w-L-R,ph=h-T-B;
 const A=t.a1-t.c1,K=t.b1+t.d1,C=t.a2-t.c2,H=t.b2+t.d2;
 const today=q=>A-K*q,future=q=>C-H*(t.S-q),pv=q=>future(q)/o.discount;
 const vals=[0,today(0),today(t.S),future(0),future(t.S),pv(0),pv(t.S)];
 const low=Math.min(...vals),high=Math.max(...vals),pad=Math.max(1,(high-low)*.08),min=low-pad,max=high+pad;
 const X=q=>L+q/t.S*pw,Y=y=>T+(max-y)/(max-min)*ph;
 const line=(x1,y1,x2,y2,color,dash='',width=2)=>`<line x1="${X(x1)}" y1="${Y(y1)}" x2="${X(x2)}" y2="${Y(y2)}" stroke="${color}" stroke-width="${width}" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
 let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Combined marginal net benefit graph. Today quantity increases to the right; future quantity increases to the left."><rect x="${L}" y="${T}" width="${pw}" height="${ph}" fill="white" stroke="#dce3eb"/>`;
 const polygon=(points,fill)=>`<polygon points="${points.map(([x,y])=>`${X(x)},${Y(y)}`).join(' ')}" fill="${fill}" opacity=".45"/>`;
 svg+=polygon([[0,0],[0,today(0)],[t.q1,today(t.q1)],[t.q1,0]],'#bbdcf7');
 svg+=polygon([[t.S-t.q2,0],[t.S-t.q2,pv(t.S-t.q2)],[t.S,pv(t.S)],[t.S,0]],'#f2cc99');
 if(o.unused>1e-7)svg+=`<rect x="${X(t.q1)}" y="${T}" width="${X(t.S-t.q2)-X(t.q1)}" height="${ph}" fill="#536478" opacity=".07"/>`;
 svg+=line(0,0,t.S,0,'#8997a6','',1);
 for(let i=0;i<=4;i++){const x=t.S*i/4,y=min+(max-min)*i/4,anchor=i===0?'start':i===4?'end':'middle';svg+=`<text x="${L-8}" y="${Y(y)+4}" text-anchor="end">${fmt(y)}</text><text x="${X(x)}" y="${h-B+23}" text-anchor="${anchor}">${fmt(x)}</text><text x="${X(x)}" y="${h-B+65}" text-anchor="${anchor}">${fmt(t.S-x)}</text>`;}
 svg+=line(0,today(0),t.S,today(t.S),'#1865ac')+line(0,future(0),t.S,future(t.S),'#ad5200')+line(0,pv(0),t.S,pv(t.S),'#ac1932','7 4',3);
 svg+=line(t.q1,0,t.q1,today(t.q1),'#1865ac','3 3')+line(t.S-t.q2,0,t.S-t.q2,pv(t.S-t.q2),'#ac1932','3 3');
 for(const [x,y,color] of [[t.q1,today(t.q1),'#1865ac'],[t.S-t.q2,pv(t.S-t.q2),'#ac1932']])svg+=`<circle cx="${X(x)}" cy="${Y(y)}" r="5" fill="${color}" stroke="white" stroke-width="2"/>`;
 if(revealed){svg+=line(o.u1,min,o.u1,max,'#172b42','2 5',1);if(t.S-o.u1-o.u2>1e-7)svg+=line(t.S-o.u2,min,t.S-o.u2,max,'#172b42','2 5',1);}
 svg+=`<text x="${L+pw/2}" y="${h-B+42}" text-anchor="middle">Today q₁ → (units)</text><text x="${L+pw/2}" y="${h-5}" text-anchor="middle">← Future q₂ (units)</text><text transform="translate(16 ${T+ph/2}) rotate(-90)" text-anchor="middle">Marginal net benefit ($ / unit)</text></svg>`;
 el.innerHTML=svg;
 $('allocation-note').textContent=`Today: ${fmt(t.q1)} units. Future: ${fmt(t.q2)} units. Unused: ${fmt(o.unused)} units. `+(o.unused>1e-7?'The gap between the selected allocations is unused stock. ':'The selected quantities meet at the same horizontal position. ')+(t.S-o.u1-o.u2>1e-7?'Stock is abundant: the optimum uses the separate zero crossings, not the curves’ intersection.':'For an interior optimum with scarce stock, the blue and dashed red curves intersect at the efficient split. At a corner, the optimum lies at an endpoint.');
}

function go(i){slide=E.clamp(i,0,4);revealed=false;history.replaceState(null,'','#'+(slide+1));render();}
document.addEventListener('click',e=>{let target=e.target.closest('button');if(!target)return;if(target.dataset.slide!==undefined)go(+target.dataset.slide);if(target.dataset.action){const action=target.dataset.action;if(action==='textbook'){t={...defaults.dynamic,a1:80,a2:80,b1:8,b2:8,c1:0,c2:0,S:10,q1:5,q2:5};revealed=false;render();return;}if(action==='optimum'){const v=E.dynamic(t);t.q1=v.u1;t.q2=v.u2;}else{let v=E.stat(s);s.p=action==='monopoly'?v.pm:v.pe;}revealed=true;refresh();}});
document.addEventListener('input',e=>{let input=e.target;if(input.dataset.choice){if(input.value===''||!input.checkValidity())return;let value=+input.value,key=input.dataset.choice;let m=dynamic()?t:s;m[key]=value;if(dynamic()){let other=key==='q1'?'q2':'q1';t[other]=Math.min(t[other],Math.max(0,t.S-value));}refresh(false);document.querySelectorAll('[data-choice]').forEach(other=>{const k=other.dataset.choice;if(other!==input)other.value=m[k];other.max=dynamic()?Math.min(t.S,t[k==='q1'?'a1':'a2']/t[k==='q1'?'b1':'b2']):s.a;});}});
document.addEventListener('change',e=>{let input=e.target;if(input.dataset.param){if(!input.checkValidity()){input.reportValidity();return;}let m=dynamic()?t:s;m[input.dataset.param]=+input.value;refresh();}if(input.dataset.choice&&!input.checkValidity()){refresh();}});
$('reset').onclick=()=>{if(dynamic())t={...defaults.dynamic};else s={...defaults.static};revealed=false;render();};$('reveal').onclick=()=>{revealed=!revealed;refresh();};$('prev').onclick=()=>go(slide-1);$('next').onclick=()=>go(slide+1);$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('fullscreen').textContent='Use browser fullscreen';}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit fullscreen':'Present fullscreen';});document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON','SUMMARY'].includes(document.activeElement.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){go(slide+1);e.preventDefault();}if(e.key==='ArrowLeft'){go(slide-1);e.preventDefault();}});window.addEventListener('hashchange',()=>go((parseInt(location.hash.slice(1))||1)-1));let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(refresh,100);});go((parseInt(location.hash.slice(1))||1)-1);

// Redraw previously hidden period plots at their actual expanded width.
document.addEventListener('toggle', e => { if(e.target.tagName==='DETAILS' && e.target.open && $('graphs').contains(e.target)) refresh(false); }, true);
